name: Django Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Start ssh-agent and load the private key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # SSH into EC2 and deploy the application
      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 13.53.131.91
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to the project directory
            cd /home/ec2-user/Django-ecom

            # Create a virtual environment and activate it
            python3 -m venv venv
            source venv/bin/activate

            # Install dependencies from requirements.txt
            pip install -r requirements.txt

            # Run migrations
            python manage.py migrate

            # (Optional) Run the Django development server (you can replace this with gunicorn or other server start commands)
            python manage.py runserver 0.0.0.0:8000 &

            and set all expeted inbound rule
            Custom TCP
            TCP
            8000
            0.0.0.0/0

