name: Django Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Start ssh-agent and load the private key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 13.53.131.91
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Ensure Python 3 is installed
            sudo yum install python3 -y
      
            # Ensure pip3 is installed
            sudo yum install python3-pip -y
      
            # Check if the virtual environment already exists
            if [ ! -d "venv" ]; then
              python3 -m venv venv  # Create virtual environment if it doesn't exist
            fi
      
            # Activate the virtual environment
            source venv/bin/activate
      
            # Upgrade pip and install requirements
            pip install --upgrade pip
            pip install -r requirements.txt
      
            # Run migrations and start the Django server
            python manage.py migrate
            python manage.py runserver
